// ─── SENIORS ────────────────────────────────────────────────────
export const mockSeniors = [
  {
    id: 's1',
    name: 'Eleanor Voss',
    age: 78,
    location: 'Pasadena, CA',
    bio: 'Retired librarian. Loves roses, mystery novels, and talking about Vermont in the 1950s.',
    joinedDate: '2026-01-10',
    tasksPosted: ['t1', 't2'],
    rating: 4.9,
  },
  {
    id: 's2',
    name: 'Harold Chen',
    age: 82,
    location: 'Arcadia, CA',
    bio: 'Former architect. Has 40 years of blueprints and a sharp wit.',
    joinedDate: '2026-01-22',
    tasksPosted: ['t3', 't4'],
    rating: 4.8,
  },
  {
    id: 's3',
    name: 'Ruth Nakamura',
    age: 75,
    location: 'Monrovia, CA',
    bio: 'Retired kindergarten teacher. Loves poetry and her two cats.',
    joinedDate: '2026-02-05',
    tasksPosted: ['t5', 't6'],
    rating: 5.0,
  },
  {
    id: 's4',
    name: 'George Adeyemi',
    age: 80,
    location: 'Arcadia, CA',
    bio: 'Retired pharmacist. His back garden is ambitious and getting away from him.',
    joinedDate: '2026-02-18',
    tasksPosted: ['t7'],
    rating: 4.7,
  },
  {
    id: 's5',
    name: 'Margaret Osei',
    age: 71,
    location: 'Temple City, CA',
    bio: 'Semi-retired seamstress. Has a pantry that needs serious organizing and great stories to share.',
    joinedDate: '2026-03-01',
    tasksPosted: ['t8'],
    rating: 4.9,
  },
]

// ─── TASKS ──────────────────────────────────────────────────────
export const mockTasks = [
  {
    id: 't1',
    seniorId: 's1',
    seniorName: 'Eleanor Voss',
    title: 'Help with front yard weeding',
    description: 'My rose beds are getting out of hand. Looking for someone to help weed and tidy up the front garden for a couple of hours. I will provide all tools and lemonade.',
    category: 'Yardwork',
    skillTags: ['gardening', 'physical activity'],
    date: '2026-05-10',
    duration: 2,
    location: 'Pasadena, CA',
    status: 'open',
    applicants: ['st2'],
  },
  {
    id: 't2',
    seniorId: 's1',
    seniorName: 'Eleanor Voss',
    title: 'Help me start writing my memoirs',
    description: 'I grew up in rural Vermont in the 1950s and I have so many stories I am afraid I will forget. I need help getting them onto paper — someone to sit with me, listen, ask questions, and help me write.',
    category: 'Memoir Project',
    skillTags: ['writing', 'listening', 'creative'],
    date: '2026-05-14',
    duration: 2,
    location: 'Pasadena, CA',
    status: 'matched',
    assignedStudentId: 'st1',
    applicants: ['st1', 'st3'],
  },
  {
    id: 't3',
    seniorId: 's2',
    seniorName: 'Harold Chen',
    title: 'Organize boxes of old blueprints',
    description: 'About 15 boxes of architectural drawings that need sorting, labeling, and stacking. Some may need photographing for digital archiving. Careful hands required.',
    category: 'Organizing',
    skillTags: ['organizing', 'careful handling', 'detail-oriented'],
    date: '2026-04-12',
    duration: 3,
    location: 'Arcadia, CA',
    status: 'completed',
    assignedStudentId: 'st1',
    applicants: ['st1'],
    rating: 5,
  },
  {
    id: 't4',
    seniorId: 's2',
    seniorName: 'Harold Chen',
    title: 'Cook a simple weekday dinner',
    description: 'Nothing fancy — a home-cooked meal for one. I am on a low-sodium diet. If you enjoy cooking and want to share a meal and good conversation, this task is for you.',
    category: 'Cooking',
    skillTags: ['cooking', 'nutrition awareness'],
    date: '2026-05-20',
    duration: 1.5,
    location: 'Arcadia, CA',
    status: 'open',
    applicants: [],
  },
  {
    id: 't5',
    seniorId: 's3',
    seniorName: 'Ruth Nakamura',
    title: 'Read poetry aloud with me',
    description: 'I have a collection of Mary Oliver and Naomi Shihab Nye I have been meaning to revisit. I would love someone to read aloud with me one afternoon a week. Tea provided.',
    category: 'Reading Aloud',
    skillTags: ['listening', 'companionship', 'creative'],
    date: '2026-05-08',
    duration: 1.5,
    location: 'Monrovia, CA',
    status: 'completed',
    assignedStudentId: 'st3',
    applicants: ['st3'],
    rating: 5,
  },
  {
    id: 't6',
    seniorId: 's3',
    seniorName: 'Ruth Nakamura',
    title: 'Help write letters to my grandchildren',
    description: 'My grandchildren are scattered across the country and I love writing to them. My eyesight makes it hard. I could use a helper to write while I dictate — or help me type.',
    category: 'Companionship',
    skillTags: ['writing', 'listening'],
    date: '2026-05-22',
    duration: 1,
    location: 'Monrovia, CA',
    status: 'open',
    applicants: ['st1'],
  },
  {
    id: 't7',
    seniorId: 's4',
    seniorName: 'George Adeyemi',
    title: 'Back garden tidy and hedge trim',
    description: 'I have a 40ft hedge that has grown wild, plus general garden tidying needed. I have all the tools. Looking for someone with energy and no fear of a challenge.',
    category: 'Yardwork',
    skillTags: ['gardening', 'physical activity'],
    date: '2026-05-17',
    duration: 3,
    location: 'Arcadia, CA',
    status: 'open',
    applicants: [],
  },
  {
    id: 't8',
    seniorId: 's5',
    seniorName: 'Margaret Osei',
    title: 'Sort and organize the pantry',
    description: 'My pantry has gotten chaotic over the years. I need someone with a good eye and patience to help me categorize, donate what is expired, and put things back in an order I can actually find.',
    category: 'Organizing',
    skillTags: ['organizing', 'detail-oriented'],
    date: '2026-05-13',
    duration: 2,
    location: 'Temple City, CA',
    status: 'open',
    applicants: ['st2'],
  },
]

// ─── STUDENTS ───────────────────────────────────────────────────
export const mockStudents = [
  {
    id: 'st1',
    name: 'Maya Reyes',
    school: 'Arcadia High School',
    schoolId: 'sch1',
    grade: 11,
    bio: 'Junior who loves creative writing and volunteering at the public library. Curious about publishing and storytelling as a career.',
    skills: ['writing', 'organizing', 'cooking', 'listening', 'detail-oriented'],
    hoursCompleted: 18,
    hoursGoal: 40,
    joinedDate: '2026-01-15',
    appliedTaskIds: ['t2', 't6'],
    sessions: [
      { taskId: 't3', taskTitle: 'Organize boxes of old blueprints', seniorName: 'Harold Chen', date: '2026-04-12', hours: 3, status: 'confirmed', rating: 5 },
      { taskId: 'tOld1', taskTitle: 'Help write a letter to family', seniorName: 'Ruth Nakamura', date: '2026-03-08', hours: 2, status: 'confirmed', rating: 5 },
      { taskId: 'tOld2', taskTitle: 'Weed front garden beds', seniorName: 'Eleanor Voss', date: '2026-02-22', hours: 2, status: 'confirmed', rating: 4 },
      { taskId: 'tOld3', taskTitle: 'Sort pantry and kitchen shelves', seniorName: 'Harold Chen', date: '2026-02-01', hours: 2.5, status: 'confirmed', rating: 5 },
      { taskId: 'tOld4', taskTitle: 'Read aloud from poetry anthology', seniorName: 'Ruth Nakamura', date: '2026-01-18', hours: 1.5, status: 'confirmed', rating: 5 },
    ],
  },
  {
    id: 'st2',
    name: 'Jordan Park',
    school: 'Arcadia High School',
    schoolId: 'sch1',
    grade: 10,
    bio: 'Sophomore interested in healthcare and working with elderly populations. Reliable and warm.',
    skills: ['cooking', 'physical activity', 'companionship', 'listening'],
    hoursCompleted: 8,
    hoursGoal: 40,
    joinedDate: '2026-02-01',
    appliedTaskIds: ['t1', 't8'],
    sessions: [
      { taskId: 'tOld5', taskTitle: 'Prepare a simple lunch', seniorName: 'Margaret Osei', date: '2026-03-14', hours: 1.5, status: 'confirmed', rating: 5 },
      { taskId: 'tOld6', taskTitle: 'Garden weeding and tidying', seniorName: 'George Adeyemi', date: '2026-02-28', hours: 2.5, status: 'confirmed', rating: 4 },
      { taskId: 'tOld7', taskTitle: 'Companionship visit and board games', seniorName: 'Ruth Nakamura', date: '2026-02-10', hours: 2, status: 'confirmed', rating: 5 },
      { taskId: 'tOld8', taskTitle: 'Help set up new tablet', seniorName: 'Harold Chen', date: '2026-02-05', hours: 1, status: 'confirmed', rating: 4 },
    ],
  },
  {
    id: 'st3',
    name: 'Sofia Nguyen',
    school: 'Arcadia High School',
    schoolId: 'sch1',
    grade: 12,
    bio: 'Senior applying to journalism programs. Passionate about storytelling, memoir, and giving older generations a real voice.',
    skills: ['writing', 'listening', 'creative', 'gardening', 'companionship'],
    hoursCompleted: 32,
    hoursGoal: 40,
    joinedDate: '2025-09-10',
    appliedTaskIds: ['t2'],
    sessions: [
      { taskId: 't5', taskTitle: 'Read poetry aloud', seniorName: 'Ruth Nakamura', date: '2026-05-08', hours: 1.5, status: 'confirmed', rating: 5 },
      { taskId: 'tOld9', taskTitle: 'Memoir session — childhood memories', seniorName: 'Eleanor Voss', date: '2026-04-20', hours: 2, status: 'confirmed', rating: 5 },
      { taskId: 'tOld10', taskTitle: 'Memoir session — school years', seniorName: 'Eleanor Voss', date: '2026-04-06', hours: 2, status: 'confirmed', rating: 5 },
      { taskId: 'tOld11', taskTitle: 'Memoir session — first job', seniorName: 'Eleanor Voss', date: '2026-03-23', hours: 2, status: 'confirmed', rating: 5 },
      { taskId: 'tOld12', taskTitle: 'Garden tidying', seniorName: 'George Adeyemi', date: '2026-03-09', hours: 2.5, status: 'confirmed', rating: 4 },
      { taskId: 'tOld13', taskTitle: 'Help organize kitchen cabinets', seniorName: 'Margaret Osei', date: '2026-02-16', hours: 2, status: 'confirmed', rating: 5 },
      { taskId: 'tOld14', taskTitle: 'Read poetry aloud', seniorName: 'Ruth Nakamura', date: '2026-01-30', hours: 1.5, status: 'confirmed', rating: 5 },
      { taskId: 'tOld15', taskTitle: 'Write thank-you letters', seniorName: 'Ruth Nakamura', date: '2026-01-12', hours: 1, status: 'confirmed', rating: 5 },
      { taskId: 'tOld16', taskTitle: 'Grocery run and put-away', seniorName: 'Harold Chen', date: '2025-12-14', hours: 1.5, status: 'confirmed', rating: 4 },
      { taskId: 'tOld17', taskTitle: 'Back garden weeding', seniorName: 'George Adeyemi', date: '2025-11-22', hours: 3, status: 'confirmed', rating: 4 },
      { taskId: 'tOld18', taskTitle: 'Sort fabric and craft supplies', seniorName: 'Margaret Osei', date: '2025-10-18', hours: 2, status: 'confirmed', rating: 5 },
      { taskId: 'tOld19', taskTitle: 'Read poetry aloud', seniorName: 'Ruth Nakamura', date: '2025-09-28', hours: 1.5, status: 'confirmed', rating: 5 },
    ],
  },
  {
    id: 'st4',
    name: 'DeShawn Morris',
    school: 'Arcadia High School',
    schoolId: 'sch1',
    grade: 11,
    bio: 'Junior with a passion for cooking. Wants to work in culinary after school. Great with low-sodium and dietary-restricted cooking.',
    skills: ['cooking', 'nutrition awareness', 'companionship', 'physical activity'],
    hoursCompleted: 14,
    hoursGoal: 40,
    joinedDate: '2026-01-28',
    appliedTaskIds: ['t4'],
    sessions: [
      { taskId: 'tOld20', taskTitle: 'Cook a weeknight dinner', seniorName: 'Harold Chen', date: '2026-04-05', hours: 1.5, status: 'confirmed', rating: 5 },
      { taskId: 'tOld21', taskTitle: 'Prepare a simple lunch', seniorName: 'Ruth Nakamura', date: '2026-03-22', hours: 1, status: 'confirmed', rating: 5 },
      { taskId: 'tOld22', taskTitle: 'Cook dinner and companionship visit', seniorName: 'Margaret Osei', date: '2026-03-05', hours: 2, status: 'confirmed', rating: 5 },
      { taskId: 'tOld23', taskTitle: 'Grocery shopping and meal prep', seniorName: 'Eleanor Voss', date: '2026-02-20', hours: 2, status: 'confirmed', rating: 5 },
      { taskId: 'tOld24', taskTitle: 'Cook a low-sodium dinner', seniorName: 'Harold Chen', date: '2026-02-08', hours: 1.5, status: 'confirmed', rating: 4 },
    ],
  },
]

// ─── SCHOOLS / COORDINATORS ──────────────────────────────────────
export const mockSchools = [
  {
    id: 'sch1',
    name: 'Arcadia High School',
    coordinator: 'Ms. Patricia Holt',
    coordinatorId: 'coord1',
    coordinatorEmail: 'pholt@arcadiahigh.edu',
    enrollmentCode: 'ARCADIA2026',
    students: ['st1', 'st2', 'st3', 'st4'],
    totalHoursLogged: 72,
    tasksCompleted: 19,
  },
]

export const mockCoordinators = [
  {
    id: 'coord1',
    name: 'Ms. Patricia Holt',
    schoolId: 'sch1',
    email: 'pholt@arcadiahigh.edu',
    joinedDate: '2025-09-01',
  },
]

export const CATEGORIES = [
  'Yardwork', 'Cooking', 'Organizing', 'Memoir Project',
  'Tech Help', 'Companionship', 'Reading Aloud', 'Errands',
  'Arts & Crafts', 'Pet Care',
]

export const SKILLS = [
  'writing', 'listening', 'cooking', 'gardening', 'organizing',
  'physical activity', 'tech-savvy', 'creative', 'detail-oriented',
  'companionship', 'nutrition awareness', 'careful handling',
]

export const mockTradeProfs = [
  {
    id: 'tp1',
    name: 'Carlos Mendez',
    trade: 'Landscaping & Horticulture',
    company: 'Mendez Garden Design',
    location: 'Pasadena, CA',
    bio: 'Third-generation landscaper. Looking for an apprentice who loves working outdoors and has an eye for design.',
    openings: 1,
    lookingFor: ['gardening', 'physical activity', 'detail-oriented'],
  },
  {
    id: 'tp2',
    name: 'Linda Tran',
    trade: 'Interior Organizing & Home Staging',
    company: 'Tran Home Solutions',
    location: 'Arcadia, CA',
    bio: 'Professional organizer and home stager. I love teaching young people the business side of transforming a space.',
    openings: 2,
    lookingFor: ['organizing', 'detail-oriented', 'creative'],
  },
  {
    id: 'tp3',
    name: 'Marcus Webb',
    trade: 'Culinary & Catering',
    company: "Webb's Table Catering",
    location: 'Monrovia, CA',
    bio: 'Catering chef running a small operation. A motivated student who loves cooking could grow into a real role here.',
    openings: 1,
    lookingFor: ['cooking', 'nutrition awareness', 'detail-oriented'],
  },
  {
    id: 'tp4',
    name: 'Priya Sharma',
    trade: 'Publishing & Life Stories',
    company: 'Sharma Editorial',
    location: 'Remote / Pasadena, CA',
    bio: 'Memoir editor and self-publishing consultant. If you helped a senior write their story and loved it — call me.',
    openings: 1,
    lookingFor: ['writing', 'listening', 'creative'],
  },
]

export const mockPathwaysCandidates = [
  {
    studentId: 'st3',
    flaggedBy: 'Ms. Patricia Holt',
    flaggedDate: '2026-03-15',
    recommendedTrade: 'Publishing & Life Stories',
    matchedProfId: 'tp4',
    note: 'Sofia has completed 32 hours, 6 memoir sessions, and every senior has raved about her. She should talk to Priya.',
    status: 'introduced',
  },
]
